### ISSUE TITLE
process sessions for GLM

### ISSUE THREAD

**Issue by alexpiet** [AllenInstitute/visual_behavior_glm_NP#3]
- [x] split into active/passive
   - [x] This is controlled by run_params
   - [x] Need to split session
- [x] cells dropping in and out?
   - [x] For now I will only address this through cell selection, and not fit the model just to certain epochs
   - [x] Make a separate issue for fitting to certain epochs (#24)
- [x] remove receptive field mapping
- [x] figure out how to bin spikes into time bins
- [x] This replaces the interpolation system
- [x] set up flexible system for altering time bins
- [x] some process for determining what the time bins should be
- [x] gaussian noise model might be a problem (#25)
- [x] extract_and_annotate_ephys
  - [x] add_engagement_labels() (I just threw an error, #24)
  - [x] process_ephys_data()
  - [x] establish_ephys_timebins()
  - [x] remove process_data

**Comment by alexpiet** [comment]
- figure out how to bin spikes into time bins
- set up flexible system for altering time bins
- some process for determining what the time bins should be
